branches:
  only:
  - deploy-ropsten

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - yarn blockchain > /dev/null &

script:
  - truffle test
  - truffle migrate --network ropsten --reset

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    CURRENT_DIR=$PWD
    cd "$TRAVIS_BUILD_DIR"
    # This clones the directory for the contract addresses.
    git clone https://github.com/PeterMPhillips/MyBit-Network.contracts.git
    cd MyBit-Network.contracts
    cp $CURRENT_DIR/networks/ropsten/contracts.json  networks/ropsten/contracts.json
    git add .
    git commit -m "Updated contracts"
    git push -f -q https://PeterMPhillips:$GITHUB_API_KEY@github.com/PeterMPhillips/MyBit-Network.contracts.git
    cd "$TRAVIS_BUILD_DIR"
  fi
