branches:
  only:
  - deploy-ropsten

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - yarn blockchain

script:
  - truffle test
  - truffle migrate --network ropsten --reset

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    CURRENT_DIR=$PWD
    cd "$TRAVIS_BUILD_DIR"
    # This clones the directory for the contract addresses.
    git clone git@github.com:PeterMPhillips/MyBit-Network.contracts.git
    cp $CURRENT_DIR/networks/ropsten-fork/contracts.json  $TRAVIS_BUILD_DIR/MyBit-Network.contracts/networks/ropsten/contracts.json
    git add .
    git commit -m "Updated contracts"
    git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/MyBit-Network.contracts.git
    cd "$TRAVIS_BUILD_DIR"
  fi
