#!/bin/bash
#Exports a chain folder to the given directory

CURRENT_DIR=$PWD
CHAIN_DIR=$1
#Move to chain directory that was passed to program
cd $CHAIN_DIR
mkdir chain
ganache-cli --networkId 70 --accounts 20 --db chain &
#Move back to directory this program is run from
cd $CURRENT_DIR
#Deploy contracts
truffle migrate --reset
#Kill ganache
pkill -f ganache-cli
#Move back to chain directory
cd $CHAIN_DIR
if [ -d .git ]; then
    echo "Updating git..."
    #Add to git
    cd chain
    git add .
    git commit -m "Updated chain"
    git push origin
fi
