#!/bin/bash
#Exports a chain folder to the given directory

CURRENT_DIR=$PWD
CHAIN_DIR=$1
#Move to chain directory that was passed to program
cd $CHAIN_DIR
if [ -d chain ]; then
  #If chain exists, remove all file within
  rm -rf chain
fi
#Create chain folder
mkdir chain
#Run ganache in background with db set to chain folder (kill any running ganache first)
pkill -f ganache-cli
ganache-cli -d --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect" --networkId 70 --accounts 20 --db chain &
#Move back to directory this program is run from
cd $CURRENT_DIR
#Deploy contracts
npx truffle migrate --reset
#Kill ganache
pkill -f ganache-cli
#Move addresses.json to chain directory
mv networks/development/contracts.json  $CHAIN_DIR
mv networks/development/accounts.json  $CHAIN_DIR
#Move back to chain directory
cd $CHAIN_DIR
#If git exists in folder, update git
if [ -d .git ]; then
  echo "Updating git..."
  #Add to git
  git add .
  git commit -m "Updated chain"
  git push origin
fi
